AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Luvrane API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENV: production
        AWS_REGION_NAME: eu-west-3

Resources:
  LuvraneAPI:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: luvrane-api
      CodeUri: .
      Handler: main.handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        API:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
      Policies:
        - AmazonS3FullAccess
        - Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
                - dsql:DbConnect
                - secretsmanager:GetSecretValue
              Resource: "*"
    Metadata:                         
      BuildMethod: python3.11